[package]
name = "xpmir-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xpmir_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
numpy = "0.16.2"
ndarray = "0.15.4"
serde = { version = "1.0", features = ["derive"] }
ciborium = { version = "0.2" }
simple-error = "0.2.3"
